apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-app
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-keycloak
    kind: ClusterSecretStore
  target:
    name: keycloak-db-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: /keycloak/db/username
    - secretKey: password
      remoteRef:
        key: /keycloak/db/password
